### ISSUE TITLE
3D visualization

### ISSUE THREAD

**Issue by alecrimi** [pelkmanslab/TissueMAPS-OLD#5] opened 2017-01-12 10:24 UTC
The 3D data haven't been tested so far a lot. It seems that the scroll Z at the bottom of the interface doesn't work properly. Namely, it doesn't change the image

**Comment by hackermd** [comment] 2017-02-02 09:23
Checking in the browser console revealed the following error:

<img width="1440" alt="screen shot 2017-01-27 at 16 43 31" src="https://cloud.githubusercontent.com/assets/6855297/22543518/1e4e73b8-e931-11e6-9030-57de1b71e468.png">

This [jQuery](https://jquery.com/) error seems to be caused by a newer version on *chimp*.

Checking versions on *chimp* and comparing them to older installations will be the next step.

**Comment by hackermd** [comment] 2017-02-13 12:02
This is fixed with commit TissueMAPS/TmUI@2f730c8.

The problem was not the jQuery version, but a race condition associated with a promise.

**Comment by hackermd** [comment] 2017-02-13 12:02
@scottberry Can you confirm?

**Comment by scottberry** [comment] 2017-02-13 12:07
I haven't been able to process any 3D data yet, due to the metaconfig failure: #22. I have a small 3D dataset from the yokogawa that I can try to upload on the test server if that is useful. Let me know if you want me to do this? @HackerMD

**Comment by hackermd** [comment] 2017-02-13 12:18
@scottberry this would be great! Keep in mind to update and re-build the client code on the test server:

```
./stop_server.sh
cd tmui/src
git pull
rm -r build
gulp build --production
cd
./start_server.sh
```

**Comment by SaadiaIftikhar** [comment] 2017-02-13 15:02
![meta_config_issue](https://cloud.githubusercontent.com/assets/11995487/22888409/def7e2c0-f205-11e6-9abf-c1bb28afe80f.png)

**Comment by SaadiaIftikhar** [comment] 2017-02-13 15:04
I put a 3D test dataset, it stops on metaconfig step.  Is this issue with all users or is it with me only? 
@alecrimi, @scottberry can you confirm from other users?

**Comment by hackermd** [comment] 2017-02-13 15:07
What does the log output say? Which microscope type? If Yokogawa, when was the dataset acquired (before or after the software update)?

**Comment by scottberry** [comment] 2017-02-13 15:07
When I can access the test image I will try it out.

**Comment by SaadiaIftikhar** [comment] 2017-02-13 15:10
![metaconfig_error_log](https://cloud.githubusercontent.com/assets/11995487/22888673/def4e4c0-f206-11e6-89aa-a26168271be5.png)

**Comment by SaadiaIftikhar** [comment] 2017-02-13 15:10
I just acquired it today from Yokogawa.

**Comment by SaadiaIftikhar** [comment] 2017-02-13 15:18
Software was updated already.

**Comment by hackermd** [comment] 2017-02-13 15:22
Looks like `TheZ` metadata is not (or no longer) available from the individual image files via Bioformats. Instead this information is provided via the `ZIndex` attribute in `MeasurementsDetail.mlf`. 

I will include this in `tmlib.workflow.metaconfig.cellvoyager.MetadataReader`.

**Comment by scottberry** [comment] 2017-02-13 15:24
OK great. Please let me know when a fix is added to the test instance and I’ll be happy to provide further testing.
Scott

**Comment by hackermd** [comment] 2017-02-13 17:00
Should be fixed with TissueMAPS/TmLibrary@f4cf0a7

**Comment by SaadiaIftikhar** [comment] 2017-02-13 18:58
This worked, I can visualize the z-slices!

**Comment by scottberry** [comment] 2017-02-14 08:24
Great. Now I just need someone to share the image of the test instance. @alecrimi

**Comment by SaadiaIftikhar** [comment] 2017-02-19 21:19
tested on small datasets and it worked.

**Closed as completed by SaadiaIftikhar** 2017-02-19 21:19 UTC
Labels: Urgent
